# Generated by Django 5.0.2 on 2024-03-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addarea',
            name='selectedFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
